### ISSUE TITLE
Cannot read property 'ifs' of undefined

### ISSUE THREAD

**Issue by elijah-ezaga** [qfox/heatfiler#17]
While profiling FileSaver.js and its minified version (https://github.com/eligrey/FileSaver.js), browser console reported above error. Screen shots below:

![bug_ifs](https://user-images.githubusercontent.com/23737739/28770698-61c2c180-75e0-11e7-9d22-89d403c935c6.png)

![bug_ifs_1](https://user-images.githubusercontent.com/23737739/28770704-65fd3d02-75e0-11e7-873a-321b64fc9fd8.png)

**Comment by qfox** [comment]
Minimal test case:
```
if (x) y;
```
Okay so it's trying to find the `ifs` stuff in global. Should be a simple fix.

**Comment by qfox** [comment]
A little weird how this never bothered me but perhaps I haven't run this with global code for a long time. I see many tests are failing as well so putting some work into that as well.
Thanks for reporting!
