### ISSUE TITLE
Illegal continue statement: 'dodist' does not denote an iteration statement

### ISSUE THREAD

**Issue by elijah-ezaga** [qfox/heatfiler#18]
Error occurred while profiling jszip.js (https://github.com/Stuk/jszip). Screenshots below:

![bug_continue](https://user-images.githubusercontent.com/23737739/28771120-e499a226-75e1-11e7-99da-9632bca1ea27.png)

![bug_continue_1](https://user-images.githubusercontent.com/23737739/28771125-e8bb27bc-75e1-11e7-817f-e6296350b562.png)

**Comment by qfox** [comment]
I'm currently able to properly parse and morph [the dev buid of jszip](https://raw.githubusercontent.com/Stuk/jszip/master/dist/jszip.js). This problem may have been fixed by other fixes today.

I'm closing this now. If you think the problem still persists please reopen it. Thanks.
