### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by elijah-ezaga** [qfox/heatfiler#19]
Happened when profiling minified version of jszip. Could be related to #18.

![bug_identifier](https://user-images.githubusercontent.com/23737739/28771253-67754b0a-75e2-11e7-8698-baefeb944836.png)

![bug_identifier_1](https://user-images.githubusercontent.com/23737739/28771255-6a374a78-75e2-11e7-9eea-837104bb15d5.png)

**Comment by qfox** [comment]
Just tried [the minified build](https://raw.githubusercontent.com/Stuk/jszip/master/dist/jszip.min.js) and it seems to translate properly now. Probably fixed in recent changes. Thanks!
